# Generated by Django 4.0.3 on 2023-01-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, choices=[(None, 'Choose your nationality'), ('Ugandan', 'Ugandan'), ('Non-Ugandan', 'Non-Uganda')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='legal_status',
            field=models.CharField(blank=True, choices=[(None, 'Choose your legal status'), ('Registered', 'Registered'), ('Nonregistered', 'Nonregistered')], max_length=1000, null=True),
        ),
    ]
