# Generated by Django 4.0.3 on 2023-01-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_nationality_alter_user_legal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_person_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legal_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
